name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python you are using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Upload files to PythonAnywhere
        env:
          API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          USERNAME: ${{ secrets.PA_USERNAME }}
        run: |
          echo "Uploading app.py to PythonAnywhere..."
          curl -v -X POST "https://www.pythonanywhere.com/api/v0/user/$USERNAME/files/path/home//mysite/app.py" \
          -H "Authorization: Token $API_TOKEN" \
          -F "content=@./app.py"

      - name: Reload PythonAnywhere web app
        env:
          API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          USERNAME: ${{ secrets.PA_USERNAME }}
        run: |
          echo "Reloading web app..."
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$USERNAME/webapps/mirzayusof.pythonanywhere.com/reload/" \
          -H "Authorization: Token $API_TOKEN"
