name: Deploiement sur PythonAnywhere

# Doc sur les github actions:
# https://docs.github.com/fr/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
# Doc de l'API PythonAnywhere pour uploader des fichiers, accéder à son token, etc :
# https://help.pythonanywhere.com/pages/API

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code depuis le dépôt github
        uses: actions/checkout@v2

      - name: Installation de Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the version of Python you are using

      - name: Installer les librairies necessaires au deploiement
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Envoi du code sur PythonAnywhere
        env:
          API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          USERNAME: ${{ secrets.PA_USERNAME }}
        run: |
          echo "Envoi du code vers PythonAnywhere"
          curl -v -X POST "https://www.pythonanywhere.com/api/v0/user/$USERNAME/files/path/home/jeandelarbrequicachelaforet/mysite/flask_app.py" \
          -H "Authorization: Token $API_TOKEN" \
          -F "content=@./app.py"
          # utilise le endpoint /api/v0/user/{username}/files/path{path}
          # cf : https://help.pythonanywhere.com/pages/API

      - name: Relancer l'application Flask sur PythonAnywhere
        env:
          API_TOKEN: ${{ secrets.PA_API_TOKEN }}
          USERNAME: ${{ secrets.PA_USERNAME }}
        run: |
          echo "Relancement"
          curl -X POST "https://www.pythonanywhere.com/api/v0/user/$USERNAME/webapps/pythonanywhere.com/reload/" \
          -H "Authorization: Token $API_TOKEN"
